### ISSUE TITLE
[Backend Developer] - Title Here

### ISSUE THREAD

**Issue by vildanzeynepkuyuk** [kamranahmedse/roadmap.sh#176]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

- You could add Firestore as a NoSQL database, because it is used a lot.
- You could add gRPC in API section
- You could update "C#" as "C# / ASP.net"
- You could add Flask / Django related with Python.

**Comment by Zenahr** [comment]
gRPC is a big one (used a lot in legacy systems and also some modern APIs as an alternative to Restful API design). It would've saved me a lot of confusion in the beginning.

Flask/Django: I would even argue that Flask would be more appropiate here since it is more lightweight which forces the developer into understanding what they are a doing at a deeper level. Probably opinionated.
